### ISSUE TITLE
Request: Blacklist item by its NBT data/tag

### ISSUE THREAD

**Issue by OhRetro** [Artillex-Studios/AxGraves#1]
### Example:
An item have a custom NBT tag of "soulbound" or "blacklisted", and if it does have the tag it gets deleted from the grave.

### Why?
This can avoid the issue of duping items, I have a soul bind "enchantment" plugin on my server and I quickly discover that I could dupe items that have been Soul bound

### Also
Please make it as an option that the graves last infinitely, so that way users who want it to last "infinitely" don't put a huge number

**Comment by BenceX100** [comment]
Which plugin is causing the dupes? Maybe it would be possible to fix it

**Comment by OhRetro** [comment]
This one, https://modrinth.com/plugin/itemsoulbind
It mainly dupes equipped armor pieces (and maybe off-hand items, haven't test it yet)

Steps to Replicate:
0. Have the itemsoulbind.keepondeath perm node
1. Bind an armor piece like a helmet using /binditem
2. Equip the Soul bounded item
3. Die
4. Go to grave and find you have a second identical helmet while the original is on your head

**Comment by OhRetro** [comment]
> Which plugin is causing the dupes? Maybe it would be possible to fix it

hello?

**Comment by BenceX100** [comment]
Try v1.3.0

**Comment by OhRetro** [comment]
Works perfectly! 👍
