### ISSUE TITLE
BUG: AxGraves only shows Armorstands

### ISSUE THREAD

**Issue by CptGummiball** [Artillex-Studios/AxGraves#12]
Hi,
AxGraves only displays Armorstands on our server. No console errors.

The armor stands don't disappear immediately after you take your items from the bottom one. They are only gone after a relogin.
![mien_errster_tot](https://github.com/Artillex-Studios/AxGraves/assets/151415484/fd671387-397d-42b9-910f-37abbbbd09d0)

**Comment by AverageGithub** [comment]
Hi! Could you please tell us what the server version is, and what fork you are using? (Spigot, Paper, etc.)

I will look into fixing this as soon as possible!

**Comment by CptGummiball** [comment]
Hi,
we use Spigot 1.20.4 and AxGraves 1.8.1

**Comment by AverageGithub** [comment]
Thank you! 

If I had to guess, I would think that Spigot is causing the issue (it works on Paper servers though), however I will try fixing this aswell.

 Sorry for the inconvenience caused once again, if I manage to fix it, it's going to be some time tomorrow afternoon (GMT+1 timezone)

**Comment by CptGummiball** [comment]
Thanks :) we will wait for it.

**Comment by CptGummiball** [comment]
Hi,
Not working until now. We use KeepInventory in meantime. We also have no clue whats the problem here. No Plugins blocking the functions, server settings are also ok.

**Comment by AverageGithub** [comment]
This is caused by your server's software being spigot for some reason, I could reproduce the issue, but couldn't figure out what exactly is causing this. Please consider switching to paper: https://papermc.io/downloads/paper

**Comment by CptGummiball** [comment]
Hi,
We uses PaperMC before and running into more than a few issues with this Server Software. So we decided to switch to Spigot.
I will take a deeper look at this issue the next days. Maybe i will find a solution.

**Comment by CptGummiball** [comment]
If a plugin doesn't work with Spigot, it might be appropriate to stop offering it in the Spigot forum and move it to Modrinth or Habour. If it is offered on Spigotmc it will only cause confusion.

This isn't meant to be a complaint, but a pointer.
