### ISSUE TITLE
Use constant asset names in releases

### ISSUE THREAD

**Issue by BrailleBennett** [Artillex-Studios/AxGraves#15]
Could you please use a constant release asset name in the GitHub releases? This way, people can use the GitHub's downloads endpoint to grab the latest release file without having to script to figure out what the asset is called. Example, instead of AxGraves1-10.jar you just name it AxGraves.jar .

**Comment by BenceX100** [comment]
We prefer the current versioning, you can probably get the latest version in some other way.
