### ISSUE TITLE
folia 1.20.6 Functional abnormality occurs

### ISSUE THREAD

**Issue by 2592019238-ai** [Artillex-Studios/AxGraves#19]
Graveyards cannot be generated normally except in the overworld
![RF%EIKEI6OG2@~N(NXL EAR](https://github.com/Artillex-Studios/AxGraves/assets/62113680/9df06648-fcae-4658-bbe6-3982d4ea5aff)
This error may not be caused by your plugin, but it is the same error before and after. Player heads are not generated except in the main world.

**Comment by BenceX100** [comment]
Not caused by axgraves.
