### ISSUE TITLE
Xp issue

### ISSUE THREAD

**Issue by SxRHunter** [Artillex-Studios/AxGraves#3]
Something wrong with the xp, i got more xp then i had before death, had about 29 levels died, and now got 52.

**Comment by BenceX100** [comment]
It is probably caused by some plugin or maybe keepinventory, can you show your plugin list?

**Comment by SxRHunter** [comment]
Sorry for the late reply.
Weirdly the glitch only happens to me, the other players don't have any issue.
Plugins:
AxGraves, FastChunkPregenerator, SkinsRestorer, spark and Unstriplog.
Datapacks:
Armored elytra, Double shulker shells {Both are by vanillatweaks} and pk waystones.
No keep inventory enabled.
Server is purpur 1.20.2.

**Comment by BenceX100** [comment]
Fixed in https://github.com/Artillex-Studios/AxGraves/releases/tag/1.4.1 thanks for reporting!
