### ISSUE TITLE
Display anomalies and data loss

### ISSUE THREAD

**Issue by YouaJing** [Artillex-Studios/AxGraves#4]
I’ve found some issues during testing on the Folia1.20.1

After players switch worlds, they are unable to see the Grave. Using /reload only reloads the hologram and not the skull entity. When players exit the game and re-enter the server, normal display is restored.
Grave data is only temporarily run within the server, with no local backup data. When the server crashes or the admin restarts the server, any Graves that are still counting down will be cleared, and player items will be permanently lost.

![e05d1f0b828870e6a4b9aeb347cf05a](https://github.com/Artillex-Studios/AxGraves/assets/115358337/e696185f-80d7-4fa1-98b8-b3e57edc21c6)

![image](https://github.com/Artillex-Studios/AxGraves/assets/115358337/f62552ef-ee2b-4956-bf67-95a7ba527d79)

**Comment by BenceX100** [comment]
Hello, can you check the latest version?

**Comment by YouaJing** [comment]
Using the latest releases, the problem still persists.

I suggest the following areas for improvement: 
①Re-render the scene after switching worlds 
②Store the data in SQLite, MySQL when each player dies, and delete it when the player collects items or the timer expires, and load the local data when the server initializes the plugin.

**Comment by AverageGithub** [comment]
Hi, about the first issue, we do resend packet entities on world change, but I don't think that event is called on Folia, as I don't think any teleport events are called on it, (for example: respawn event, teleport event).
